name: Deploy to Azure

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Site
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true
      
      - name: Build
        run: hugo --minify
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: public
          path: ./public
          retention-days: 1

  deploy_dev:
    runs-on: ubuntu-latest
    name: Deploy to DEV
    needs: build
    environment: DEV
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: public
          path: ./public
      
      - name: Delete existing files from Azure Storage (DEV)
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az storage blob delete-batch \
              --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME_DEV }} \
              --account-key ${{ secrets.AZURE_STORAGE_ACCOUNT_KEY_DEV }} \
              --source '$web'
      
      - name: Deploy to Azure Storage Static Website (DEV)
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az storage blob upload-batch \
              --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME_DEV }} \
              --account-key ${{ secrets.AZURE_STORAGE_ACCOUNT_KEY_DEV }} \
              --destination '$web' \
              --source ./public \
              --overwrite

  deploy_pro:
    runs-on: ubuntu-latest
    name: Deploy to PRO
    needs: deploy_dev
    environment: PRO
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: public
          path: ./public
      
      - name: Delete existing files from Azure Storage (PRO)
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az storage blob delete-batch \
              --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME_PRO }} \
              --account-key ${{ secrets.AZURE_STORAGE_ACCOUNT_KEY_PRO }} \
              --source '$web'
      
      - name: Deploy to Azure Storage Static Website (PRO)
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az storage blob upload-batch \
              --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME_PRO }} \
              --account-key ${{ secrets.AZURE_STORAGE_ACCOUNT_KEY_PRO }} \
              --destination '$web' \
              --source ./public \
              --overwrite
